  pipeline {
    agent {
      node {
        label "master"
      } 
    }
    parameters {
        choice(
            choices: ['Apply' , 'Destroy'],
            description: 'Do you like to execute "apply" or "destroy" terraform?',
            name: 'REQUESTED_ACTION')
    }

    stages {
      stage('fetch_latest_code') {
        steps {
          git url: 'https://github.com/Omidznlp/AWS-Self-Maneged-Kubernetes.git'
        }
      }

      stage('TF Init&Plan') {
        when {
                expression { params.REQUESTED_ACTION == 'Apply' }
            }
        steps {
          withAWS(credentials: 'terraform-credentials') {
          sh 'terraform -chdir=terraform init'
          sh 'terraform -chdir=terraform plan'
          }
        }
              
      }

      stage('Approval') {
          when {
                expression { params.REQUESTED_ACTION == 'Apply' }
            }
        steps {
          script {
            def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
          }
        }
      }

      stage('TF Apply') {
          when {
                expression { params.REQUESTED_ACTION == 'Apply' }
            }
        steps {
          withAWS(credentials: 'terraform-credentials') {
          sh 'terraform -chdir=terraform apply -input=false --auto-approve'
          }
        }
      }
      stage('Removal') {
          when {
                expression { params.REQUESTED_ACTION == 'Destroy' }
            }
        steps {
          script {
            def userInput = input(id: 'confirm', message: 'Destroy Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Destroy terraform', name: 'confirm'] ])
          }
        }
      }

      stage('TF Destroy') {
            when {
                expression { params.REQUESTED_ACTION == 'Destroy' }
            }
        steps {
          withAWS(credentials: 'terraform-credentials') {
          sh 'terraform -chdir=terraform destroy -input=false --auto-approve'
          }
        }
      }
    } 
  }